/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecipesRouteImport } from './routes/_recipes'
import { Route as RecipesIndexRouteImport } from './routes/_recipes/index'
import { Route as RecipesNewRouteImport } from './routes/_recipes/new'
import { Route as RecipesRecipeIdIndexRouteImport } from './routes/_recipes/$recipeId/index'
import { Route as PublicRecipesRecipeIdRouteImport } from './routes/public/recipes/$recipeId'
import { Route as RecipesRecipeIdEditRouteImport } from './routes/_recipes/$recipeId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/_recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => RecipesRoute,
} as any)
const RecipesRecipeIdIndexRoute = RecipesRecipeIdIndexRouteImport.update({
  id: '/$recipeId/',
  path: '/$recipeId/',
  getParentRoute: () => RecipesRoute,
} as any)
const PublicRecipesRecipeIdRoute = PublicRecipesRecipeIdRouteImport.update({
  id: '/public/recipes/$recipeId',
  path: '/public/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdEditRoute = RecipesRecipeIdEditRouteImport.update({
  id: '/$recipeId/edit',
  path: '/$recipeId/edit',
  getParentRoute: () => RecipesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/new': typeof RecipesNewRoute
  '/': typeof RecipesIndexRoute
  '/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/public/recipes/$recipeId': typeof PublicRecipesRecipeIdRoute
  '/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/new': typeof RecipesNewRoute
  '/': typeof RecipesIndexRoute
  '/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/public/recipes/$recipeId': typeof PublicRecipesRecipeIdRoute
  '/$recipeId': typeof RecipesRecipeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_recipes': typeof RecipesRouteWithChildren
  '/login': typeof LoginRoute
  '/_recipes/new': typeof RecipesNewRoute
  '/_recipes/': typeof RecipesIndexRoute
  '/_recipes/$recipeId/edit': typeof RecipesRecipeIdEditRoute
  '/public/recipes/$recipeId': typeof PublicRecipesRecipeIdRoute
  '/_recipes/$recipeId/': typeof RecipesRecipeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/new'
    | '/'
    | '/$recipeId/edit'
    | '/public/recipes/$recipeId'
    | '/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/new'
    | '/'
    | '/$recipeId/edit'
    | '/public/recipes/$recipeId'
    | '/$recipeId'
  id:
    | '__root__'
    | '/_recipes'
    | '/login'
    | '/_recipes/new'
    | '/_recipes/'
    | '/_recipes/$recipeId/edit'
    | '/public/recipes/$recipeId'
    | '/_recipes/$recipeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RecipesRoute: typeof RecipesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PublicRecipesRecipeIdRoute: typeof PublicRecipesRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_recipes': {
      id: '/_recipes'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_recipes/': {
      id: '/_recipes/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/_recipes/new': {
      id: '/_recipes/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/_recipes/$recipeId/': {
      id: '/_recipes/$recipeId/'
      path: '/$recipeId'
      fullPath: '/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdIndexRouteImport
      parentRoute: typeof RecipesRoute
    }
    '/public/recipes/$recipeId': {
      id: '/public/recipes/$recipeId'
      path: '/public/recipes/$recipeId'
      fullPath: '/public/recipes/$recipeId'
      preLoaderRoute: typeof PublicRecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_recipes/$recipeId/edit': {
      id: '/_recipes/$recipeId/edit'
      path: '/$recipeId/edit'
      fullPath: '/$recipeId/edit'
      preLoaderRoute: typeof RecipesRecipeIdEditRouteImport
      parentRoute: typeof RecipesRoute
    }
  }
}

interface RecipesRouteChildren {
  RecipesNewRoute: typeof RecipesNewRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  RecipesRecipeIdEditRoute: typeof RecipesRecipeIdEditRoute
  RecipesRecipeIdIndexRoute: typeof RecipesRecipeIdIndexRoute
}

const RecipesRouteChildren: RecipesRouteChildren = {
  RecipesNewRoute: RecipesNewRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  RecipesRecipeIdEditRoute: RecipesRecipeIdEditRoute,
  RecipesRecipeIdIndexRoute: RecipesRecipeIdIndexRoute,
}

const RecipesRouteWithChildren =
  RecipesRoute._addFileChildren(RecipesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  RecipesRoute: RecipesRouteWithChildren,
  LoginRoute: LoginRoute,
  PublicRecipesRecipeIdRoute: PublicRecipesRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
