/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRouteImport } from './routes/join'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeHomeIdRouteImport } from './routes/home/$homeId'
import { Route as HomeHomeIdRecipesRouteImport } from './routes/home/$homeId/recipes'
import { Route as HomeHomeIdPantryRouteImport } from './routes/home/$homeId/pantry'
import { Route as HomeHomeIdGroceryListRouteImport } from './routes/home/$homeId/grocery-list'
import { Route as HomeHomeIdCalendarRouteImport } from './routes/home/$homeId/calendar'

const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeIdRoute = HomeHomeIdRouteImport.update({
  id: '/home/$homeId',
  path: '/home/$homeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHomeIdRecipesRoute = HomeHomeIdRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => HomeHomeIdRoute,
} as any)
const HomeHomeIdPantryRoute = HomeHomeIdPantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => HomeHomeIdRoute,
} as any)
const HomeHomeIdGroceryListRoute = HomeHomeIdGroceryListRouteImport.update({
  id: '/grocery-list',
  path: '/grocery-list',
  getParentRoute: () => HomeHomeIdRoute,
} as any)
const HomeHomeIdCalendarRoute = HomeHomeIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HomeHomeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/home/$homeId': typeof HomeHomeIdRouteWithChildren
  '/home/$homeId/calendar': typeof HomeHomeIdCalendarRoute
  '/home/$homeId/grocery-list': typeof HomeHomeIdGroceryListRoute
  '/home/$homeId/pantry': typeof HomeHomeIdPantryRoute
  '/home/$homeId/recipes': typeof HomeHomeIdRecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/home/$homeId': typeof HomeHomeIdRouteWithChildren
  '/home/$homeId/calendar': typeof HomeHomeIdCalendarRoute
  '/home/$homeId/grocery-list': typeof HomeHomeIdGroceryListRoute
  '/home/$homeId/pantry': typeof HomeHomeIdPantryRoute
  '/home/$homeId/recipes': typeof HomeHomeIdRecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/join': typeof JoinRoute
  '/home/$homeId': typeof HomeHomeIdRouteWithChildren
  '/home/$homeId/calendar': typeof HomeHomeIdCalendarRoute
  '/home/$homeId/grocery-list': typeof HomeHomeIdGroceryListRoute
  '/home/$homeId/pantry': typeof HomeHomeIdPantryRoute
  '/home/$homeId/recipes': typeof HomeHomeIdRecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/home/$homeId'
    | '/home/$homeId/calendar'
    | '/home/$homeId/grocery-list'
    | '/home/$homeId/pantry'
    | '/home/$homeId/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/join'
    | '/home/$homeId'
    | '/home/$homeId/calendar'
    | '/home/$homeId/grocery-list'
    | '/home/$homeId/pantry'
    | '/home/$homeId/recipes'
  id:
    | '__root__'
    | '/'
    | '/join'
    | '/home/$homeId'
    | '/home/$homeId/calendar'
    | '/home/$homeId/grocery-list'
    | '/home/$homeId/pantry'
    | '/home/$homeId/recipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JoinRoute: typeof JoinRoute
  HomeHomeIdRoute: typeof HomeHomeIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$homeId': {
      id: '/home/$homeId'
      path: '/home/$homeId'
      fullPath: '/home/$homeId'
      preLoaderRoute: typeof HomeHomeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/$homeId/recipes': {
      id: '/home/$homeId/recipes'
      path: '/recipes'
      fullPath: '/home/$homeId/recipes'
      preLoaderRoute: typeof HomeHomeIdRecipesRouteImport
      parentRoute: typeof HomeHomeIdRoute
    }
    '/home/$homeId/pantry': {
      id: '/home/$homeId/pantry'
      path: '/pantry'
      fullPath: '/home/$homeId/pantry'
      preLoaderRoute: typeof HomeHomeIdPantryRouteImport
      parentRoute: typeof HomeHomeIdRoute
    }
    '/home/$homeId/grocery-list': {
      id: '/home/$homeId/grocery-list'
      path: '/grocery-list'
      fullPath: '/home/$homeId/grocery-list'
      preLoaderRoute: typeof HomeHomeIdGroceryListRouteImport
      parentRoute: typeof HomeHomeIdRoute
    }
    '/home/$homeId/calendar': {
      id: '/home/$homeId/calendar'
      path: '/calendar'
      fullPath: '/home/$homeId/calendar'
      preLoaderRoute: typeof HomeHomeIdCalendarRouteImport
      parentRoute: typeof HomeHomeIdRoute
    }
  }
}

interface HomeHomeIdRouteChildren {
  HomeHomeIdCalendarRoute: typeof HomeHomeIdCalendarRoute
  HomeHomeIdGroceryListRoute: typeof HomeHomeIdGroceryListRoute
  HomeHomeIdPantryRoute: typeof HomeHomeIdPantryRoute
  HomeHomeIdRecipesRoute: typeof HomeHomeIdRecipesRoute
}

const HomeHomeIdRouteChildren: HomeHomeIdRouteChildren = {
  HomeHomeIdCalendarRoute: HomeHomeIdCalendarRoute,
  HomeHomeIdGroceryListRoute: HomeHomeIdGroceryListRoute,
  HomeHomeIdPantryRoute: HomeHomeIdPantryRoute,
  HomeHomeIdRecipesRoute: HomeHomeIdRecipesRoute,
}

const HomeHomeIdRouteWithChildren = HomeHomeIdRoute._addFileChildren(
  HomeHomeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JoinRoute: JoinRoute,
  HomeHomeIdRoute: HomeHomeIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
